system:
  name: "Golf Swing Analyzer"
  version: "1.0.0"
  log_level: "INFO"
  
ble:
  device_name: "GolfSwingAnalyzer"
  service_uuid: "12345678-1234-1234-1234-123456789abc"
  characteristic_uuid: "87654321-4321-4321-4321-cba987654321"
  connection_timeout: 30
  scan_timeout: 10
  retry_attempts: 3
  
data_processing:
  sample_rate: 100  # Hz
  filter_type: "complementary"
  filter_alpha: 0.98
  swing_detection_threshold: 2.0  # m/s²
  min_swing_duration: 0.5  # seconds
  max_swing_duration: 3.0  # seconds
  
physics:
  ball_mass: 0.04593  # kg (standard golf ball)
  ball_diameter: 0.04267  # m
  air_density: 1.225  # kg/m³ at sea level
  gravity: 9.81  # m/s²
  drag_coefficient: 0.47
  magnus_coefficient: 0.5
  club_head_efficiency: 1.4  # speed transfer ratio
  
websocket:
  host: "localhost"
  port: 8765
  ping_interval: 20
  ping_timeout: 10
  
api:
  host: "0.0.0.0"
  port: 8000
  reload: true
  
calibration:
  gravity_threshold: 0.5  # m/s²
  stationary_time: 2.0  # seconds
  auto_calibrate: true